### ISSUE TITLE
Is there a way to force the application to use english?

### ISSUE THREAD

**Issue by 4lphac** [IllusionMods/AI-Girl-Translations#24]
Hello! It's not directly related to your work but maybe you know this game better than me..
 
I'm running under wine+ubuntu and everything works correctly apart from language, it's stuck in Japanese. Main menu is ok, but all the rest is in Japanese. If I try to run from the same folder in a windows WM, english  works fine (but too slow). 
Do you know a way to force English? Or where the game looks to choose the correct language?

Thanks

**Comment by ManlyMarco** [comment]
It could be anything, send your output_log.txt from game root.
